name: app_phys
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch-cuda=12.4
  - pytorch
  - torchaudio
  - torchvision
  - matplotlib
  - numpy
  - pillow
  - ipykernel
  - jupyter_client
  - pip